// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwv2H0--OlfgR82YG5NBdlud1IYX5xXIU',
    appId: '1:380852729926:web:221a43c625781cd6bab247',
    messagingSenderId: '380852729926',
    projectId: 'skillaid-237d1',
    authDomain: 'skillaid-237d1.firebaseapp.com',
    storageBucket: 'skillaid-237d1.firebasestorage.app',
    measurementId: 'G-5SXGZH7TDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEQG6vPxH5ZsahRjT2s8SVxU9chdhybBM',
    appId: '1:380852729926:android:8b86108f4b83936dbab247',
    messagingSenderId: '380852729926',
    projectId: 'skillaid-237d1',
    storageBucket: 'skillaid-237d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkpIp5-TrD4mrXJoO5IhuzgZh92PECl4s',
    appId: '1:380852729926:ios:8cfcd997444ea4a0bab247',
    messagingSenderId: '380852729926',
    projectId: 'skillaid-237d1',
    storageBucket: 'skillaid-237d1.firebasestorage.app',
    iosBundleId: 'com.example.skillaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkpIp5-TrD4mrXJoO5IhuzgZh92PECl4s',
    appId: '1:380852729926:ios:8cfcd997444ea4a0bab247',
    messagingSenderId: '380852729926',
    projectId: 'skillaid-237d1',
    storageBucket: 'skillaid-237d1.firebasestorage.app',
    iosBundleId: 'com.example.skillaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwv2H0--OlfgR82YG5NBdlud1IYX5xXIU',
    appId: '1:380852729926:web:d9d228d7525757b6bab247',
    messagingSenderId: '380852729926',
    projectId: 'skillaid-237d1',
    authDomain: 'skillaid-237d1.firebaseapp.com',
    storageBucket: 'skillaid-237d1.firebasestorage.app',
    measurementId: 'G-55C281DDPL',
  );

}